Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to display the numbers of a series 1,3,9,27,81...n by using the for loop.

#include <iostream.h>
#include <conio.h>
void main() {
clrscr();
int n,num,i;
cout << "How many number in series: ";
cin >> n;
cout << "\nRequired series: ";
num = 1;
for(i=0;i<n;i++)
{
	cout<<num<<" ";
	num=num*3;
}
getch();
}

/*
=================OUTPUT==================
How many number in series: 4

Required series: 1 3 9 27
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
