#include <iostream.h>
#include <conio.h>
void main() {
clrscr();
int n,sum;
n=1;
sum=0;
while(n<=100) {
sum =sum + n;
n++;
}
cout << "sum of first hundered number (1 to 100): " << sum;
getch();
}

/*
========================OUTPUT=====================
sum of first hundered number (1 to 100): 5050
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
