#include <iostream.h>
#include <conio.h>
void main() {
clrscr();
int i;
for(i=48;i<=57;i++) {
cout << char(i)<< char(i)<<" ";
}
getch();
}


/*
=======OUTPUT========================
00 11 22 33 44 55 66 77 88 99
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
