#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
int age;
float weight;
cout << "Enter age and weight of donor: ";
cin >> age >> weight;
if(age>=18 && age<=55 && weight>45)
	cout << "\nPerson is eligible for donating blood.";
else
	cout << "\nPerson is not eligible for donating blood.";
getch();
}

/*
=====================OUTPUT==========================
Enter age and weight of donor: 16
40

Person is not eligible for donating blood.
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
