Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to enter to numbers. Make a comparision between them with a conditional operator. If the first number is greater than the second, perform multiplication otherwise perform division operation.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
int a,b;
cout << "Enter two numbers:";
cin >> a >> b;
if(a>b)
	cout << "Multiplicatiion=" << a*b;
else
	cout << "Division is=" << a/b;
getch();
}
/*
=====================OUTPUT====================
Enter two numbers:12
2
Multiplicatiion=24
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
