Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to print whether the number entered is even or odd. Use conditional operator.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
int a;
cout << "Enter a number: ";
cin >> a;
if(a%2==0)
	cout << "\nEntered number " << a << " is even.";
else
	cout << "\nEntered number "  << a << " is odd.";
getch();
}

/*
=====================OUTPUT==========================
Enter a number: 26

Entered number 26 is even.
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
