Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to enter two numbers and find the smallest out of them. Use conditional operator.

 #include <iostream.h>
 #include <conio.h>
 void main() {
 clrscr();
 int x,y;
 cout << "Enter two numbers: ";
 cin >> x >> y;
 if(x<y)
	 cout << x << " is smallest.";
else
	 cout << y << " is smallest.";
getch();
}




/*
====================OUTPUT=======================
Enter two numbers: 12
6
6 is smallest.
*/















                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
