#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
int age;
cout << "\nEnter age of the person to vote: ";
cin >> age;
if(age>=18)
	cout << "\nEligible.";
else
	cout << "\nNot-eligible.";
getch();
}

/*
=======================OUTPUT====================

Enter age of the person to vote: 20

Eligible.
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
