Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to find the average temperature of five sunny days. Assume the temperature in Celsius.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
	int d1,d2,d3,d4,d5;
	float avg;
	cout << "Enter temperature of 5 days in celsius: ";
	cin >> d1 >> d2 >> d3 >> d4 >> d5;
	avg=(d1+d2+d3+d4+d5)/5.0;
	cout << "Average temperature of five days= " << avg;
getch();
}


/*
==============OUTPUT=================
Enter temperature of 5 days in celsius: 22
25
27
32
28
Average temperature of five days= 26.799999
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
