Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to calculate the total cost of the vehicle by adding basic cost with (i)excise duty(15%); (ii) sales tax(10%) (iii) octroi (5%) and (iv) road tax (1%). Input the basic cost.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
float basic,ex,st,oct,rd,total;
	cout << "Enter basic cost of vehicle: ";
	cin >> basic;
	ex=basic*15/100;
	st=basic*10/100;
	oct=basic*5/100;
	rd=basic*1/100;
	total=basic+ex+st+oct+rd;
	cout << "Total cost= " << total;
getch();
}

/*
================OUTPUT=======================
Enter basic cost of vehicle: 84000
Total cost= 110040
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
