Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to enter a number that should be less than 100 and greater than 9. Display the number in reverse order using modular division and division operation.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
	int n,d1,d2;
	cout << "Enter a number: ";
	cin >> n;
	d1=n%10;
	d2=n/10;
	n=d1*10+d2;
	cout << "After reverse number is " << n << ".";
getch();
}


/*
====================OUTPUT=====================
Enter a number: 25
After reverse number is 52.
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
