Name: Parth Bhatia								Date: 5/12/2014
STD/DIV: XI/H									Roll No: 3
Title: WAP to input the rainfall of three consecutive days in CMS(Centi-Meters) and find its average.

#include<iostream.h>
#include<conio.h>
void main() {
clrscr();
	float r1,r2,r3,avg;
	cout << "Enter rainfall of three days: ";
	cin >> r1 >> r2 >> r3;
	avg=(r1+r2+r3)/3;
	cout << "\nAverage rainfall= " << avg;
getch();
}
/*
================OUTPUT====================
Enter rainfall of three days: 31
35
29

Average rainfall= 31.666666
*/
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                

